Grid X: 20
Grid Y: 20
Init X Coord: 0
Init Y Coord: 0
Coord Label Template: x_#_y_#
N Regions: 8
Regions Labels:
  - House 1
  - House 2
  - Tacos
  - Cheese
  - House 3
  - House 4
  - Grocer
  - Pizza
Lower Left Cells X:
  - 2 #House 1 
  - 7 #House 2
  - 12 #Tacos
  - 17 #Cheese
  - 17 #House 3
  - 16 #House 4
  - 10 #Grocer
  - 0 #Pizza
Lower Left Cells Y:
  - 0 #House 1 
  - 2 #House 2
  - 1 #Tacos
  - 7 #Cheese
  - 11 #House 3
  - 17 #House 4
  - 10 #Grocer
  - 15 #Pizza
Upper Right Cells X:
  - 4 #House 1 
  - 9 #House 2
  - 18 #Tacos
  - 19 #Cheese
  - 19 #House 3
  - 18 #House 4
  - 14 #Grocer
  - 6 #Pizza
Upper Right Cells Y:
  - 2 #House 1 
  - 4 #House 2
  - 5 #Tacos
  - 9 #Cheese
  - 15 #House 3
  - 19 #House 4
  - 19 #Grocer
  - 18 #Pizza
Region Colors:
  - mediumseagreen #House 1 
  - mediumseagreen #House 2
  - darkgoldenrod #Tacos
  - gold  #Cheese
  - mediumseagreen #House 3
  - mediumseagreen #House 4
  - skyblue #Grocer
  - firebrick #Pizza