version: '3.8'

services:
  ws:
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - .:/root/grapefruit
    command: tail -f /dev/null  # Temporary command to keep the container running