Grid X: 5
Grid Y: 5
Init X Coord: 0
Init Y Coord: 0
Coord Label Template: x_#_y_#
Region Labels:
  - p1
  - tacos
  - pizza
  - mud
PRL Cost Objectives:
  - Energy
  - Time

PRL Default Cost: # Default PRL cost for transitions
  PRL Cost Mean:
    - 5.0
    - 10.0
  PRL Cost Covariance: # Unique elements (upper triangular)
    - 1.0 # 11
    - 0.2 # 12
    - 0.5 # 22
p1:
  Bounds:
    - 2
    - 2
    - 0
    - 0
  Color: mediumseagreen
tacos:
  Bounds:
    - 4
    - 4
    - 1
    - 1
  Color: darkgoldenrod
pizza:
  Bounds:
    - 2
    - 2
    - 4
    - 4
  Color: tomato
mud:
  Bounds:
    - 1
    - 4
    - 2
    - 2
  Color: sienna
  PRL Cost Mean: # Water takes more energy, but is quicker
    - 20.0
    - 5.0
  PRL Cost Covariance: # Unique elements (upper triangular)
    - 5.0 # 11
    - 0.1 # 12
    - 1.5 # 22