Grid X: 22
Grid Y: 20
Init X Coord: 0
Init Y Coord: 19
Coord Label Template: x_#_y_#
Region Labels:
  - Base_1
  - Base_2
  - Deposit
  - Sun_1
  - Sun_2
  - Sun_3
  - Sun_4
  - Wash
  - Sample_1
  - Sample_2
  - Mud_1
  - Mud_2
  - Mud_3

PRL Cost Objectives:
  - Time
  - Exposure

# Ensures that all covariances are positive semi-definite (multiplies each covariance by itself)
Square Covariance: True 

# Preference distribution
PRL Preference: 
  Mean:
    - 100.0
    - 20.0
  Covariance: # Unique elements (upper triangular)
    - 200.0 # 11
    - -90.0 # 12
    - 50.0 # 22

# Default PRL cost for transitions
PRL Default Cost: 
  Mean:
    - 1.0
    - 0.1
  Covariance: # Unique elements (upper triangular)
    - 0.2 # 11
    - 0.0 # 12
    - 0.01 # 22

# Regions
Base_1:
  Bounds:
    - 0 
    - 8 
    - 14 
    - 19 
  Color: cadetblue 
  Fancy: False
  Proposition: Base
Base_2:
  Bounds:
    - 4 
    - 8 
    - 11 
    - 13 
  Color: cadetblue 
  Fancy: False
  Proposition: Base

Deposit:
  Bounds:
    - 0 
    - 2 
    - 15 
    - 15 
  Color: chartreuse 

Wash:
  Bounds:
    - 2 
    - 3 
    - 11 
    - 12 
  Color: aqua 
  PRL Cost Mean: 
    - 10.0
    - 30.0
  PRL Cost Covariance: # Unique elements (upper triangular)
    - 2.5 # 11
    - 1.5 # 12
    - 8.0 # 22

Sample_1: # in the sun
  Bounds:
    - 0 
    - 5 
    - 0 
    - 4 
  Color: coral
  PRL Cost Mean: 
    - 5.0
    - 15.0
  PRL Cost Covariance: # Unique elements (upper triangular)
    - 1.8 # 11
    - 0.1 # 12
    - 5.0 # 22
  Proposition: Sample
  Alpha: 1.0

Sample_2: # out of the sun
  Bounds:
    - 15 
    - 16 
    - 1 
    - 2 
  Color: coral
  PRL Cost Mean: 
    - 5.0
    - 0.0
  PRL Cost Covariance: # Unique elements (upper triangular)
    - 1.0 # 11
    - 0.0 # 12
    - 0.0 # 22
  Proposition: Sample
  Alpha: 1.0

Mud_1:
  Bounds:
    - 0
    - 7
    - 7
    - 8
  Color: peru
  PRL Cost Mean: 
    - 2.0
    - 6.0
  PRL Cost Covariance: # Unique elements (upper triangular)
    - 0.5 # 11
    - 0.8 # 12
    - 2.0 # 22
  Proposition: Mud
  Fancy: false
  Alpha: 1.0

Mud_2:
  Bounds:
    - 0
    - 4
    - 5
    - 6
  Color: peru
  PRL Cost Mean: 
    - 2.0
    - 6.0
  PRL Cost Covariance: # Unique elements (upper triangular)
    - 0.5 # 11
    - 0.8 # 12
    - 2.0 # 22
  Proposition: Mud
  Fancy: false
  Alpha: 1.0

Mud_3:
  Bounds:
    - 6
    - 11
    - 0
    - 5
  Color: peru
  PRL Cost Mean: 
    - 2.0
    - 6.0
  PRL Cost Covariance: # Unique elements (upper triangular)
    - 0.5 # 11
    - 0.8 # 12
    - 2.0 # 22
  Proposition: Mud
  Fancy: false
  Alpha: 1.0

Sun_1:
  Bounds:
    - 9
    - 13
    - 11
    - 16
  Color: yellow
  PRL Cost Mean: 
    - 0.0
    - 3.0
  PRL Cost Covariance: # Unique elements (upper triangular)
    - 0.0 # 11
    - 0.8 # 12
    - 0.5 # 22
  Proposition: Sun
  Fancy: false

Sun_2:
  Bounds:
    - 0
    - 3
    - 11
    - 12
  Color: yellow
  PRL Cost Mean: 
    - 0.0
    - 3.0
  PRL Cost Covariance: # Unique elements (upper triangular)
    - 0.0 # 11
    - 0.8 # 12
    - 0.5 # 22
  Proposition: Sun
  Fancy: false

Sun_3:
  Bounds:
    - 0
    - 13
    - 0
    - 10
  Color: yellow
  PRL Cost Mean: 
    - 0.0
    - 3.0
  PRL Cost Covariance: # Unique elements (upper triangular)
    - 0.0 # 11
    - 0.8 # 12
    - 0.5 # 22
  Proposition: Sun
  Fancy: false

Sun_4:
  Bounds:
    - 0
    - 13
    - 0
    - 10
  Color: yellow
  PRL Cost Mean: 
    - 0.0
    - 3.0
  PRL Cost Covariance: # Unique elements (upper triangular)
    - 0.0 # 11
    - 0.8 # 12
    - 0.5 # 22
  Proposition: Sun
  Fancy: false

Obstacles:
  base_wall_1:
    Bounds:
      - 6
      - 8
      - 11
      - 14
  base_wall_2:
    Bounds:
      - 0
      - 4
      - 13
      - 14
  base_wall_3:
    Bounds:
      - 3
      - 4
      - 15
      - 17
  base_wall_4:
    Bounds:
      - 4
      - 4
      - 11
      - 12
  base_wall_5:
    Bounds:
      - 1
      - 1
      - 11
      - 12
  base_wall_6:
    Bounds:
      - 6
      - 8
      - 16
      - 17
  rock_1:
    Bounds:
      - 9
      - 17
      - 17
      - 17
  rock_2:
    Bounds:
      - 17
      - 17
      - 4
      - 16
  rock_3:
    Bounds:
      - 14
      - 14
      - 0
      - 13
  rock_4:
    Bounds:
      - 15
      - 21
      - 0
      - 0
  rock_5:
    Bounds:
      - 18
      - 20
      - 4
      - 8
  rock_6:
    Bounds:
      - 19
      - 21
      - 12
      - 13
  rock_7:
    Bounds:
      - 18
      - 20
      - 17
      - 18
  rock_8:
    Bounds:
      - 18
      - 19
      - 3
      - 3
