Grid X: 20
Grid Y: 20

Region Labels:
  - Base
  - Deposit
  - Wash
  - Sample
  - Mud

# Preference distribution
PRL Preference: 
  Mean:
    - 100.0
    - 10.0
  Covariance: # Unique elements (upper triangular)
    - 0.1 # 11
    - 0.0 # 12
    - 0.1 # 22

Base:
  N Cells: 2

Deposit:
  N Cells: 1

Wash:
  N Cells: 2

Sample:
  N Cells: 5

Mud:
  N Cells: 40

Obstacles: 40

True Mean Lower Bound: 
  - 2.0
  - 0.1
True Mean Upper Bound: 
  - 10.0
  - 1.0

Estimate Mean Lower Bound: 
  - 0.0
  - 0.0
Estimate Mean Upper Bound: 
  - 0.0
  - 0.0