Grid X: 15
Grid Y: 15

Region Labels:
  - Base
  - Deposit
  - Wash
  - Sample
  - Mud

# Preference distribution
PRL Preference: 
  Mean:
    - 76.0
    - 10.0
  Covariance: # Unique elements (upper triangular)
    - 50.0 # 11
    - 10.0 # 12
    - 70.0 # 22

Base:
  N Cells: 15

Deposit:
  N Cells: 4

Wash:
  N Cells: 5

Sample:
  N Cells: 10

Mud:
  N Cells: 30

Obstacles: 40

True Mean Lower Bound: 2.0
True Mean Upper Bound: 10.0
Estimate Mean Lower Bound: 5.0
Estimate Mean Upper Bound: 13.0